# Generated by Django 4.2.6 on 2023-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIEAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Img',
            field=models.ImageField(default=12.05, upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
